# epgbcn4 aka seikath@gmail.com
# is410@epg-mysql-memo1:~/bin/epg.mysql.cluster.restore.sh
# 2013-02-17.03.42.08

ndbd[1]=10.95.109.195
ndbd[2]=10.95.109.196

ndb_mgmd[1]=10.95.109.216
ndb_mgmd[2]=10.95.109.217

LocalBackupDirName="backup/BACKUP"

ssh_command="ssh -T -p 22"

DEBUG=1 # active
DEBUG=0 # deactivated 


# add error handling array here for later handling via looping the array
restore_error_match[0]="Unable to find table:"
restore_error_text[0]="The restore FAILED due to missing/broken tables!"


# ERROR 1051 (42S02): Unknown table 
# Could not create hashmap "DEFAULT-HASHMAP-3840-2": 299: Operation not allowed or aborted due to single user mode
# Restore: Failed to restore table: sys/def/14/users_3b1c9c31 ... Exiting 
# Backup Id = 12
# Nodeid = 3
# backup path = /data/mysqlcluster/backup/BACKUP/BACKUP-12
# Opening file '/data/mysqlcluster/backup/BACKUP/BACKUP-12/BACKUP-12.3.ctl'
# File size 87368 bytes
# Backup version in files: ndb-6.3.11 ndb version: mysql-5.5.29 ndb-7.2.10
# Stop GCP of Backup: 710143
# Connected to ndb!!
# 
# NDBT_ProgramExit: 1 - Failed

# Second failure : after initial -m restore
# Backup Id = 12
# Nodeid = 3
# backup path = /data/mysqlcluster/backup/BACKUP/BACKUP-12
# Opening file '/data/mysqlcluster/backup/BACKUP/BACKUP-12/BACKUP-12.3.ctl'
# File size 87368 bytes
# Backup version in files: ndb-6.3.11 ndb version: mysql-5.5.29 ndb-7.2.10
# Stop GCP of Backup: 710143
# Connected to ndb!!
# Create table `connect/def/auth_group_permissions` failed: 721: Schema object with given name already exists
# Restore: Failed to restore table: `connect/def/auth_group_permissions` ... Exiting 
# 
# NDBT_ProgramExit: 1 - Failed 


# restore missing table 
#         is410@epg-mysql-memo1:[Sun Feb 17 16:01:08][~/epg-mysql-cluster/bin](git::activating.metadata.restore)$ sudo ndb_restore -m --include-tables=connect.django_admin_log -c 10.95.109.216 -b 12 -n 3 -r /data/mysqlcluster/backup/BACKUP/BACKUP-12
#         Backup Id = 12
#         Nodeid = 3
#         backup path = /data/mysqlcluster/backup/BACKUP/BACKUP-12
#         Including tables: connect.django_admin_log 
#         Opening file '/data/mysqlcluster/backup/BACKUP/BACKUP-12/BACKUP-12.3.ctl'
#         File size 87368 bytes
#         Backup version in files: ndb-6.3.11 ndb version: mysql-5.5.29 ndb-7.2.10
#         Stop GCP of Backup: 710143
#         Connected to ndb!!
#         Successfully restored table `connect/def/django_admin_log`
#         Successfully restored table event REPL$connect/django_admin_log
#         Successfully created index `PRIMARY` on `django_admin_log`
#         Successfully created index `django_admin_log_e4470c6e` on `django_admin_log`
#         Successfully created index `django_admin_log_fbfc09f1` on `django_admin_log`
#         Opening file '/data/mysqlcluster/backup/BACKUP/BACKUP-12/BACKUP-12-0.3.Data'
#         File size 77726988 bytes
#         _____________________________________________________
#         Processing data in table: connect/def/auth_group_permissions(8) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/auth_user_user_permissions(9) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/devices(10) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/django_admin_log(11) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/users(14) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/NDB$BLOB_23_2(24) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/auth_user_groups(15) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/NDB$BLOB_11_4(12) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/NDB$BLOB_11_7(13) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/auth_user(16) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/auth_group(17) fragment 0
#         _____________________________________________________
#         Processing data in table: sys/def/NDB$EVENTS_0(3) fragment 0
#         _____________________________________________________
#         Processing data in table: mysql/def/NDB$BLOB_4_3(5) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/django_session(18) fragment 0
#         _____________________________________________________
#         Processing data in table: sys/def/SYSTAB_0(2) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/django_content_type(20) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/auth_permission(21) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/NDB$BLOB_18_1(19) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/registration_attempts(22) fragment 0
#         _____________________________________________________
#         Processing data in table: mysql/def/ndb_schema(4) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/auth_message(23) fragment 0
#         _____________________________________________________
#         Processing data in table: mysql/def/ndb_apply_status(6) fragment 0
#         _____________________________________________________
#         Processing data in table: connect/def/crm_adminprofile(25) fragment 0
#         Opening file '/data/mysqlcluster/backup/BACKUP/BACKUP-12/BACKUP-12.3.log'
#         File size 52 bytes
#         Restored 194 tuples and 0 log entries
# 
#         NDBT_ProgramExit: 0 - OK

# restore data at mising table : 
# is410@epg-mysql-memo1:[Sun Feb 17 16:03:04][~/epg-mysql-cluster/bin](git::activating.metadata.restore)$ sudo ndb_restore --include-tables=connect.django_admin_log -c 10.95.109.216 -b 12 -n 3 -r /data/mysqlcluster/backup/BACKUP/BACKUP-12
# Backup Id = 12
# Nodeid = 3
# backup path = /data/mysqlcluster/backup/BACKUP/BACKUP-12
# Including tables: connect.django_admin_log 
# Opening file '/data/mysqlcluster/backup/BACKUP/BACKUP-12/BACKUP-12.3.ctl'
# File size 87368 bytes
# Backup version in files: ndb-6.3.11 ndb version: mysql-5.5.29 ndb-7.2.10
# Stop GCP of Backup: 710143
# Connected to ndb!!
# Unable to find table: `django_admin_log`
# Restore: Failed to restore table: `connect/def/django_admin_log` ... Exiting 
# 
# NDBT_ProgramExit: 1 - Failed


# 2013-02-17.16.05.32 no initial start  
# is410@epg-mysql-memo1:[Sun Feb 17 16:05:18][~/epg-mysql-cluster/bin](git::activating.metadata.restore)$ echo "ps axu | grep  ndbd" | ssh -T is410@10.95.109.195
# root     13553  0.0  0.0  99000  2440 ?        Ss   16:05   0:00 /usr/sbin//ndbd --ndb-nodeid=3 --ndb-connectstring=10.95.109.216:1186,10.95.109.217:1186 --nostart
# root     13554  1.5  1.1 2398164 93660 ?       SLl  16:05   0:00 /usr/sbin//ndbd --ndb-nodeid=3 --ndb-connectstring=10.95.109.216:1186,10.


# is410@epg-mysql-memo1:[Sun Feb 17 16:15:28][~/epg-mysql-cluster/bin](git::activating.metadata.restore)$ echo "ps axu | grep  ndbd" | ssh -T is410@10.95.109.196
# root     18875  0.0  0.0  99000  2444 ?        Ss   16:15   0:00 /usr/sbin//ndbd --ndb-nodeid=4 --ndb-connectstring=10.95.109.216:1186,10.95.109.217:1186 --nostart
# root     18876  1.0  0.9 2398164 93472 ?       SLl  16:15   0:00 /usr/sbin//ndbd --ndb-nodeid=4 --ndb-connectstring=10.95.109.216:1186,10.95.109.217:1186 --nostart
# is410    18895  0.0  0.0 103232   888 ?        S    16:15   0:00 grep ndbd


# is410@epg-mysql-memo1:[Sun Feb 17 16:15:32][~/epg-mysql-cluster/bin](git::activating.metadata.restore)$ sudo ndb_restore --include-tables=connect.django_admin_log -c 10.95.109.216 -b 12 -n 3 -r /data/mysqlcluster/backup/BACKUP/BACKUP-12
# Backup Id = 12
# Nodeid = 3
# backup path = /data/mysqlcluster/backup/BACKUP/BACKUP-12
# Including tables: connect.django_admin_log 
# Opening file '/data/mysqlcluster/backup/BACKUP/BACKUP-12/BACKUP-12.3.ctl'
# File size 87368 bytes
# Backup version in files: ndb-6.3.11 ndb version: mysql-5.5.29 ndb-7.2.10
# Stop GCP of Backup: 710143
# Failed to initialize consumers
# 
# NDBT_ProgramExit: 1 - Failed


# Case the ndb data nodes not started after stop/start 
# is410@epg-mysql-memo1:[Sun Feb 17 20:33:12][~/epg-mysql-cluster/bin](git::activating.metadata.restore)$ ndb_mgm -c 10.95.109.216 -e 'show'
# Connected to Management Server at: 10.95.109.216:1186
# Cluster Configuration
# ---------------------
# [ndbd(NDB)]	2 node(s)
# id=3	@10.95.109.195  (mysql-5.5.29 ndb-7.2.10, not started)
# id=4	@10.95.109.196  (mysql-5.5.29 ndb-7.2.10, not started)
# 
# is410@epg-mysql-memo1:[Sun Feb 17 20:33:37][~/epg-mysql-cluster/bin](git::activating.metadata.restore)$ ndb_mgm -c 10.95.109.216 -e 'all start'
# Connected to Management Server at: 10.95.109.216:1186
# NDB Cluster is being started.
# NDB Cluster is being started.
# is410@epg-mysql-memo1:[Sun Feb 17 20:35:56][~/epg-mysql-cluster/bin](git::activating.metadata.restore)$ ndb_mgm -c 10.95.109.216 -e '4 status'
# Connected to Management Server at: 10.95.109.216:1186
# Node 4: started (mysql-5.5.29 ndb-7.2.10)
# 
# is410@epg-mysql-memo1:[Sun Feb 17 20:36:15][~/epg-mysql-cluster/bin](git::activating.metadata.restore)$ ndb_mgm -c 10.95.109.216 -e '3 status'
# Connected to Management Server at: 10.95.109.216:1186
# Node 3: started (mysql-5.5.29 ndb-7.2.10)



